"""empty message

Revision ID: 957bdea9baa6
Revises: cab7e4d3a551
Create Date: 2022-10-21 07:41:21.880645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957bdea9baa6'
down_revision = 'cab7e4d3a551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('venue', 'genres', existing_type=sa.String(120), type_=sa.ARRAY(sa.String))
    op.alter_column('artist', 'genres', existing_type=sa.String(120), type_=sa.ARRAY(sa.String))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'created_at')
    op.alter_column('venue', 'genres', existing_type=sa.ARRAY(sa.String), type_=sa.String(120)) 
    op.alter_column('artist', 'genres', existing_type=sa.ARRAY(sa.String), type_=sa.String(120))
    # ### end Alembic commands ###
