"""empty message

Revision ID: ca05b047c903
Revises: 22be5a77a666
Create Date: 2022-10-18 14:04:41.182001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca05b047c903'
down_revision = '22be5a77a666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_at')
    # ### end Alembic commands ###
