"""empty message

Revision ID: cab7e4d3a551
Revises: ca05b047c903
Create Date: 2022-10-20 23:22:17.979330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cab7e4d3a551'
down_revision = 'ca05b047c903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)         
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)           
    # ### end Alembic commands ###
